### ISSUE TITLE
Is there a mesh for the x8 aircraft?

### ISSUE THREAD

**Issue by zimmy87** [AOS55/Fixedwing-Airsim#35]
Hi I'm currently running the main.py with the x8 aircraft configuration file. Is there an x8 mesh available for changing the drone appearance in AirSim?

**Comment by AOS55** [comment]
Hey zimmy you should be able to grab a stl file from and use this in the airsim config, I think you specify a path in the airsim.json file, there is several you can download https://grabcad.com/library/tag/x8. I'm not sure how this mesh will deal with collisions though.
